- hosts: webserver
  become: true
  tasks:
    - name: Install Web Tier Components
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: Start apache
      service:
        name: apache2
        state: started
        enabled: yes
        
    - name: Enable mod-wsgi
      apache2_module:
        name: wsgi
        state: present
        notify: Restart Apache
  
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
