- hosts: loadbalancer
  become: true
  tasks:
    - name: Stop nginx
      service:
        name: nginx
        state: stopped

- hosts: webserver
  become: true
  tasks:
    - name: Stop Apache
      service:
        name: apache2
        state: stopped

- hosts: database
  become: true
  tasks:
    - name: Restart mysql
      service:
        name: mysql
        state: restart

- hosts: webserver
  become: true
  tasks:
    - name: Start Apache
      service:
        name: apache2
        state: started

- hosts: loadbalancer
  become: true
  tasks:
    - name: Start nginx
      service:
        name: nginx
        state: started
